# Generated by Django 4.2.17 on 2024-12-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_customer_options_alter_myuser_options_and_more'),
        ('profiles_and_pets', '0002_alter_pet_owner_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.customer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auths.myuser'),
        ),
    ]
