# Generated by Django 4.2.17 on 2024-12-05 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles_and_pets', '0003_alter_pet_owner_alter_profile_user'),
        ('auths', '0002_alter_customer_options_alter_myuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('total_stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Done')])),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_and_pets.pet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_and_products.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.staff')),
            ],
            options={
                'verbose_name': 'Service Detail',
                'verbose_name_plural': 'Service Details',
                'db_table': 'service_details',
            },
        ),
        migrations.AddConstraint(
            model_name='servicedetails',
            constraint=models.UniqueConstraint(fields=('pet', 'service'), name='unique_pet_service'),
        ),
    ]
